### ISSUE TITLE
lock_screen_slideshow.sh: Desktop Slideshow not re-enabled properly

### ISSUE THREAD

**Issue by PicoMitchell** [smurphos/nemo_actions_and_cinnamon_scripts#1]
The `gsettings set org.cinnamon.desktop.background picture-uri` command seems to cause the desktop slideshow to be disabled even if it is paused. I'm going to look into detecting if the slideshow was running and then re-enabling it instead of using the `gsettings set org.cinnamon.desktop.background.slideshow slideshow-paused` command. I'll post back if that works but I wanted to get the bug report out first.

**Comment by PicoMitchell** [comment]
Remembering and then re-setting "slideshow-enabled" seems to be the way to go.

This code works properly:

`  # Screensaver active loop.
  while $(qdbus org.cinnamon.ScreenSaver /org/cinnamon/ScreenSaver org.cinnamon.ScreenSaver.GetActive) == true
  do
    # If screensaver just activated pause native background slide-show, get user background and either set static
    # lock screen background or start slideshow
    if ( ! $ACTIVE ) ; then
      PREVIOUS_SLIDESHOW_STATE=$(gsettings get org.cinnamon.desktop.background.slideshow slideshow-enabled) # Remember previous desktop slideshow state because setting picture-uri will automatically disable the desktop slideshow.
      DESK_BACKGROUND=$(gsettings get org.cinnamon.desktop.background picture-uri)
      ACTIVE=true
      if ( ! $SLIDESHOW ) ; then
        gsettings set org.cinnamon.desktop.background picture-uri "file://$STATIC_BACKGROUND"
      fi
      TIMER="$INTERVAL"
    fi
    # Update background if in slideshow mode
    if ( $SLIDESHOW ); then
      if [ $TIMER == $INTERVAL ] ; then
        LOCK_BACKGROUND=$(find "$SLIDESHOW_DIR" -iname '*.jp*g' -o -iname '*.png' | shuf -n1)
        gsettings set org.cinnamon.desktop.background picture-uri "file://$LOCK_BACKGROUND"
        TIMER=0
      fi
      ((TIMER++))
    fi
    sleep 1
  done 
  # Set background back to the user background and unpause native slideshow on screensaver de-activation
  if ( $ACTIVE ) ; then
      if ( $PREVIOUS_SLIDESHOW_STATE ) ; then
        # There is no point resetting the previous background when slideshow was enabled because it will get changed immedately when slideshow is re-enabled.
        gsettings set org.cinnamon.desktop.background.slideshow slideshow-enabled "$PREVIOUS_SLIDESHOW_STATE"
      else
        gsettings set org.cinnamon.desktop.background picture-uri "$DESK_BACKGROUND"
      fi
      ACTIVE=false
  fi`

**Comment by smurphos** [comment]
Thanks for the report and suggested fix - I'll do some testing my end and update.

**Comment by smurphos** [comment]
Thanks again for the suggested fix - works well my end  and implemented - https://github.com/smurphos/nemo_actions_and_cinnamon_scripts/commit/9d8e504a8655732ce81f6c8eb2186d2a8f7fda55

**Comment by PicoMitchell** [comment]
Thanks so much for all these quick fixes!
