### ISSUE TITLE
close all except current window

### ISSUE THREAD

**Issue by blueray453** [smurphos/nemo_actions_and_cinnamon_scripts#12]
I have a script to close all except current window.

```
#!/bin/bash

not_to_close=$(xdotool selectwindow)
selected_window_class_name=$(xprop -id $not_to_close WM_CLASS | cut -d '"' -f2)

for i in $(xdotool search --desktop 0 --class "$selected_window_class_name"); do
    if [ "$not_to_close" != "$i" ]; then
        xdotool windowclose "$i"
    fi
done
```
How can I make a action from it which only shows in the file browser and not desktop?

**Comment by smurphos** [comment]
Sorry for very delayed response. Good question - https://github.com/linuxmint/nemo/blob/master/files/usr/share/nemo/actions/sample.nemo_action

There's a condition to limit actions to the desktop context menu only, but not vice-versa. 

So what you might need to do it right a second script to check that nemo is the focussed application and use the exit code of that script as a Condition

e.g. in your action something like - Conditions=exec <action_scripts/check_nemo_foreground.sh>;

And the script would be something like

```
#!/bin/bash
if wmctrl -lx | grep "$(printf 0x0%x "$(xdotool getactivewindow)")" | grep nemo.Nemo; then
 exit 0
fi
exit 1
```

I've not tested this - but it should work...
