### ISSUE TITLE
Sorting nemo actions does't work

### ISSUE THREAD

**Issue by OmeCor** [smurphos/nemo_actions_and_cinnamon_scripts#15]
The script provided to sort Nemo actions does not sort actions, neither by alphabet, nor by date. In fact, it appears not to do anything at all. Nemo actions are displayed in an order that I do not understand. The order does not change in between sessions.
The shell script 'sort_actions.sh' does run and does not generate any errors.
Nemo version installed: 4.4.3
![sort_actions](https://user-images.githubusercontent.com/68194771/114310706-f5659780-9aeb-11eb-9793-631a4c73cd4f.png)

These are the names of the corresponding nemo_action files:
![nemo_actons_order](https://user-images.githubusercontent.com/68194771/114311042-69ed0600-9aed-11eb-9718-7b62411d05c0.png)

This is my setup, by the way:
![system info_neofetch](https://user-images.githubusercontent.com/68194771/114310868-aa984f80-9aec-11eb-87f5-49c44e2dc7e5.png)

**Comment by LaurentOngaro** [comment]
You can find a solution to sort the actions in the [following thread
](https://stackoverflow.com/questions/57279720/determine-nemo-context-menu-actions-ordering)

**Comment by smurphos** [comment]
Lol, that script was the same one used in the action the OP was querying.
The sorting in the menu doesn't look right for the file modification dates. However I've deprecated that action now - I'd really suggest upgrading to Mint 20 or later where you get sensible native sorting of actions.
