### ISSUE TITLE
How do I set Steam games to not be opacified in opacify_windows.sh

### ISSUE THREAD

**Issue by adrummer354** [smurphos/nemo_actions_and_cinnamon_scripts#16]
How do I modify or update the opacify_windows.sh to make sure there is 100% exclusion of all games run through Steam application

**Comment by smurphos** [comment]
Apologies for the delayed response - as per the scripts comments you need to identify the window class of your game window and add them as an exclude in the script (line EXCLUDE_CLASS=) Sorry don't know if Steam games share a common class which would make things easier.

`wmctrl -lx` in a terminal whilst a game is running to identify the class.
