### ISSUE TITLE
lock_screen_slideshow.sh: Not Launching from .desktop file

### ISSUE THREAD

**Issue by PicoMitchell** [smurphos/nemo_actions_and_cinnamon_scripts#2]
I've found that the `for PID in $(pgrep -f "${0##*/}"); do` loop seems to think the script is already running when it is launched from a .desktop launcher because "sh -c lock_screen_slideshow.sh" is in the list of running processes.

A simple (but not foolproof) workaround would be to only care about processes that have a slash before the script name with: `for PID in $(pgrep -f "/${0##*/}"); do`

**Comment by smurphos** [comment]
Thanks for the report and the suggested fix - I'll test and update.

**Comment by smurphos** [comment]
Hi,

I went for an alternative method which I hope is more robust.

```
if pidof -o %PPID -x "${0##*/}"; then
  exit 1
fi
```
From testing the methods in a terminal....
```
steve@steve-HP-Pavilion-g6-Notebook-PC:~$ pidof -o %PPID -x "lock_screen_slideshow.sh"
28881 28877
steve@steve-HP-Pavilion-g6-Notebook-PC:~$ pgrep -fa "lock_screen_slideshow.sh"
16948 geany /home/steve/.local/bin/lock_screen_slideshow.sh
28876 sh -c lock_screen_slideshow.sh
28877 /bin/bash /home/steve/.local/bin/lock_screen_slideshow.sh
28881 /bin/bash /home/steve/.local/bin/lock_screen_slideshow.sh
```
Thanks again for reporting the issue.

Fixed by https://github.com/smurphos/nemo_actions_and_cinnamon_scripts/commit/6854ec894be989512b4677491cec5f1e776987c2
