### ISSUE TITLE
Feature: Add a new nemo_action script for hyper.js

### ISSUE THREAD

**Issue by bizprat** [smurphos/nemo_actions_and_cinnamon_scripts#20]
Hi,
I have created a new nemo_action script for [hyper.js](https://hyper.is/). I wanted it to be like whenever I right-click in any folder, I get the option to open it with the hyper.js terminal.

Here is the script, kindly add it to this repository

```
[Nemo Action]

Active=true
Name=Open with Hyper
Comment=Open the Hyper.js Terminal for %P
#Exec=<hyper %P> (If symlink is made in current directory)
Exec=/opt/Hyper/hyper %P
Icon-Name=hyper
Selection=none
Extensions=dir
Terminal=false
```

**Comment by smurphos** [comment]
Hi, thanks for suggesting - it seems a bit niche. I understand the Cinnamon devs plan to add a Nemo Action section to Cinnamon Spices in the near future - once that is up and running that may be a good place to add your action.

Hint - you probably want a `Dependencies=/opt/Hyper/hyper;` line in your action
