### ISSUE TITLE
lock_screen_slideshow.desktop: Does not work on autostart

### ISSUE THREAD

**Issue by PicoMitchell** [smurphos/nemo_actions_and_cinnamon_scripts#3]
I've found that this .desktop launcher works when double-clicked but does not work on autostart. I'm not sure exactly why, but I tracked the issue back to `[en_GB]` (and I am in the US). If I remove `[en_GB]` completely from both line, the it autostarts properly.

**Comment by smurphos** [comment]
Thanks again. I wasn't aware that locale mismatches cause an issue. I'll test and update.

**Comment by smurphos** [comment]
Fixed by https://github.com/smurphos/nemo_actions_and_cinnamon_scripts/commit/9fa4a652c78c1e872ebd93fa837ca68a427c6c0c
