### ISSUE TITLE
lock_screen_slideshow.sh: qdbus not pre-installed on Mint 19.1

### ISSUE THREAD

**Issue by PicoMitchell** [smurphos/nemo_actions_and_cinnamon_scripts#4]
FYI, qdbus does not come installed on a clean install of Linux Mint 19.1.

Just wanted to let you know so that it can be listed as a requirement when folks are trying to set this up.

**Comment by smurphos** [comment]
Thanks - I've just taken a look on my system and yet it was available as a dependency of an installed app

**Comment by smurphos** [comment]
Fixed by https://github.com/smurphos/nemo_actions_and_cinnamon_scripts/commit/c63f32e5e98e884eb81e2dedf039741dbab416a9
