### ISSUE TITLE
workspace_background_switcher.sh: can I pass a parameter to kill the process

### ISSUE THREAD

**Issue by znbn** [smurphos/nemo_actions_and_cinnamon_scripts#5]
Thanks for the little great script.

I was modifing it to load my /home/jack/.backgrounds/image[0..4] and It could be useful to reload or to kill the process.

Two more parameters for the script:
--kill to unload it
--reload to kill and restart with the new parameters

bye, Giacomo

**Comment by smurphos** [comment]
Thanks for the feedback and the suggestion and sorry for the delayed reply.

I'll have a think about a kill option.
 
In the meantime I've amended the scripts so any relaunch will kill previous running instances rather than exiting the new instance - i.e. the default is now a --reload.
