### ISSUE TITLE
lock_screen_slideshow.sh: Images very dark

### ISSUE THREAD

**Issue by samgreco** [smurphos/nemo_actions_and_cinnamon_scripts#7]
I tried to post this on your thread in the Mint forums, but they disallowed it because the thread was too old. (?)

Slideshow works great.  Except that the images are dark.  Bot sure if I am missing something, but I don't see anything to change that, or what might be causing it.

**Comment by smurphos** [comment]
Hi,

That's a 'feature' of cinnamon-screensaver - you can modify it via the instructions here - https://forums.linuxmint.com/viewtopic.php?p=1616145#p1616145

**Comment by samgreco** [comment]
Thanks!  Exactly what I needed.  This is one one of my screens from my automation server running home assistant.  It's an in-wall touchscreen.  The wife loves the random pics that popup on the wall.
