### ISSUE TITLE
dimming instead of opacity in opacify_windows.sh

### ISSUE THREAD

**Issue by exces-s** [smurphos/nemo_actions_and_cinnamon_scripts#8]
Hello. 
It's just a stupid question: Is there any way to rewrite `opacify_windows.sh` in such a way that unfocused windows become slightly more darker then active (I use Mint Cinnamon 20)? 
I tried dumbly replace `_NET_WM_WINDOW_OPACITY` by `_NET_WM_WINDOW_BRIGHTNESS` but it doesn't work. I tried to google `_NET_WM_WINDOW`-props, but didn't success in that.

**Comment by smurphos** [comment]
Hi, sorry I don't think so. Brightness per se is a function of the whole screen. Other than the Window Opacity any other visual change between focused and unfocused windows will be down to the GTK / Controls theme in use.
